#include "pitches.h"

int melody[] = {
  NOTE_AS4, NOTE_AS4, NOTE_A4, NOTE_A4, NOTE_GS4, NOTE_GS4, NOTE_GS4, NOTE_GS4, NOTE_F4,
  NOTE_GS4, NOTE_GS4, NOTE_FS4, NOTE_FS4, NOTE_DS4, NOTE_DS4, NOTE_DS4, NOTE_DS4,
  NOTE_AS4, NOTE_AS4, NOTE_CS5, NOTE_CS5, NOTE_DS5, NOTE_DS5, NOTE_DS5, NOTE_DS5, NOTE_CS5,
  NOTE_DS5, NOTE_DS5, NOTE_CS5, NOTE_CS5, NOTE_AS4, NOTE_AS4, NOTE_AS4
};
